---
functional:
  - Пользователь должен иметь возможность зарегистрироваться через e-mail
  - Пользователь должен иметь возможность зарегистрироваться через учетную запись GitHub
  - Пользователь должен иметь возможность авторизоваться через e-mail
  - Пользователь должен иметь возможность авторизоваться через GitHub
  - Пользователь должен иметь возможность авторизоваться через Discord
  - Пользователь должен иметь возможность восстановить пароль через e-mail
  - Пользователь должен иметь возможность просмотреть профиль любого игрока
  - Пользователь должен иметь возможность просмотреть таблицу лидеров
  - Пользователь должен иметь возможность наблюдать за игрой другого пользователя
  - Пользователь не должен иметь возможность вносить изменения в код наблюдаемой игры других игроков
  - Пользователь должен иметь возможность просматривать историю любой игры
  - Пользователь не должен иметь возможность участвовать в нескольких играх одновременно
non-functional:
  - Cайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность сменить язык отображения сайта
  - Пользователь не должен иметь возможность изменять параметры после старта игры
  - Пользователь должен иметь возможность предложить сопернику поставить паузу в текущей игре
  - Пользователь должен иметь возможность предложить сопернику изменить время игры
  - Пользователь должен иметь возможность просмотреть список игроков в on-line
